### ISSUE TITLE
help im in chapter 5 and the player is invisible only his gun is showed

### ISSUE THREAD

**Issue by osam7a** [PacktPublishing/Hands-On-Unity-2021-Game-Development-Second-Edition#2]

**Comment by rajat-packt** [comment]
Hey @osam7a 
Can you provide anymore details regarding the issue you are facing, some sort of error code, or logs?
We won't be able to assist you in a meaningful way without more details.

**Comment by rajat-packt** [comment]
Closing for now, until more details are provided.
